### ISSUE TITLE
Rig importer appends all collections

### ISSUE THREAD

**Issue by Endertainer007** [BlueEvilGFX/MC-Assets-Manager#2]
So I have an issue with the rig importer where it will append all collections inside a blend file. This is an issue with rigs that uses multiple collections for organizational purposes.

![blender_7it1BkIvlx](https://user-images.githubusercontent.com/57242521/183273128-6f66cefe-adea-4eaa-9bdd-8bec7a4ab222.png)

My suggestion is to make the rig importer only append a specific collection with a prefix. For example, the rig importer only appends a collection with the McAM_ prefix and it will append that collection with any collection or items inside. So if there's a collection like McAM_Main > Second \ Third > Fourth, it will only append the McAM_Main collection and the Second collection inside while leaving the Third and Fourth collection unappended.

![blender_av1snpNLLG](https://user-images.githubusercontent.com/57242521/183273544-194431d0-456c-4f53-9ba6-1502c2d0518d.png)

**Comment by Endertainer007** [comment]
One odd thing I found is that the unwanted collections seem to be linked to the ones in the main collection.

![image](https://user-images.githubusercontent.com/57242521/183274040-9d621c23-c36a-4163-8460-03a2cbf4433c.png)

And moving the unwanted collections back into the main collection seems to fix it.

![image](https://user-images.githubusercontent.com/57242521/183274074-87cbd256-3203-4ea9-b67b-c46949fabd82.png)

But then, why does the importer create extra linked collections?

**Comment by BlueEvilGFX** [comment]
Thanks for the issue.
I will take a closer look at it.  Creating a prefix system can at least fix the first "issue" which you address. Although I wanted to make it as intuitiv as possible (appending just everything) it seems that someone might want to have more control what to append exactly. 

**But why would you want that exactly?** The preset file should only contain the preset otherwise there is wasted space 


For the second issue: i will need to look at it. It seems a bit odd yes

Thanks for everything ;)

**Comment by BlueEvilGFX** [comment]
Your second issue has now been resolved. I fixed it. Not it looks like following when you append either an asset (which will be appended as a collection and not as an object), rigs or presets:
![image](https://user-images.githubusercontent.com/107540992/183287844-a67bd25f-5964-4cc4-8f85-97ae142172d0.png)
Implementing your first *issue* will be my next goal.
Thanks for opening the issue so far!
It will all come with the update v0.1.8

**Comment by BlueEvilGFX** [comment]
I have fixed the issue now. Icons might not work correctly with the collection restriction appending yet. I would need some more testing with it first. But the other featues do work now.
For restrict the appending to one collection just add "&&" and then the collection name afterwards like this:
![image](https://user-images.githubusercontent.com/107540992/183290058-3b1c862f-6e79-4292-948e-2b9d722c28da.png)
But it only support a restriction to **one** collection. It will append everything if there is not the additional information in the file name. An example for that would be this:
![image](https://user-images.githubusercontent.com/107540992/183290089-065c6166-d324-4944-9899-6804a032ac8a.png)

Thanks for reporting :)
